In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.naive_bayes import GaussianNB

import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [2]:
df = pd.read_csv (f"F:\\Courses\\Data Science bootcamp\\archive\\telco_customer_pre.csv")

In [23]:
df.isnull().sum()

gender              0
Partner             0
Dependents          0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Churn               0
customerID          0
SeniorCitizen       0
tenure              0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [3]:
ndf = df.drop(["customerID"], axis = 1)

In [4]:
ndf.head()

gender  Partner  Dependents  PhoneService  MultipleLines  InternetService  \
0     0.0      0.0         0.0           0.0            0.0              0.0   
1     1.0      1.0         0.0           1.0            1.0              0.0   
2     1.0      1.0         0.0           1.0            1.0              0.0   
3     1.0      1.0         0.0           0.0            0.0              0.0   
4     0.0      1.0         0.0           1.0            1.0              1.0   

   OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
0             0.0           0.0               0.0          0.0          0.0   
1             1.0           1.0               1.0          0.0          0.0   
2             1.0           0.0               0.0          0.0          0.0   
3             1.0           1.0               1.0          1.0          0.0   
4             0.0           1.0               0.0          0.0          0.0   

   StreamingMovies  Contract  PaperlessBilling  PaymentMethod  Churn  \
0              0.0       0.0               0.0            0.0    0.0   
1              0.0       1.0               1.0            1.0    0.0   
2              0.0       0.0               0.0            1.0    1.0   
3              0.0       1.0               1.0            2.0    0.0   
4              0.0       0.0               0.0            0.0    1.0   

   SeniorCitizen  tenure  MonthlyCharges  TotalCharges  
0              0       1           29.85         29.85  
1              0      34           56.95       1889.50  
2              0       2           53.85        108.15  
3              0      45           42.30       1840.75  
4              0       2           70.70        151.65

In [16]:
ndf.shape

(7043, 20)

In [5]:
X = ndf.iloc[:, :-1].values
y = ndf.iloc[:, 4].values 

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 


In [7]:
# Standardize features by removing mean and scaling to unit variance:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test) 


In [8]:
# Use the KNN classifier to fit data:
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train) 


KNeighborsClassifier()

In [9]:
# Predict y data with classifier: 
y_predict = classifier.predict(X_test)
# Print results: 
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict)) 

[[123   0   0]
 [  0 638  28]
 [  0  21 599]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       123
         1.0       0.97      0.96      0.96       666
         2.0       0.96      0.97      0.96       620

    accuracy                           0.97      1409
   macro avg       0.97      0.97      0.97      1409
weighted avg       0.97      0.97      0.97      1409



In [17]:
# Organize data:
#label_names = y
labels = y
#feature_names = data['feature_names']
features = X
# Print data:
print('Class label = ', labels[0])
print(features[0])

Class label =  0.0
[ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    1.   29.85]


In [21]:
features.shape

(7043, 19)

In [11]:
# Split dataset into random train and test subsets:
train, test, train_labels, test_labels = train_test_split(features, labels, test_size=0.33, random_state=42)
# Initialize classifier:
gnb = GaussianNB()
# Train the classifier:
model = gnb.fit(train, train_labels)
# Make predictions with the classifier:
predictive_labels = gnb.predict(test)
print(predictive_labels)
# Evaluate label (subsets) accuracy:
print(accuracy_score(test_labels, predictive_labels))

[0. 2. 1. ... 2. 2. 2.]
1.0


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 1.00


In [14]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[ 205    0    0]
 [   0 1016    0]
 [   0    0  892]]


In [15]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00       205
         1.0       1.00      1.00      1.00      1016
         2.0       1.00      1.00      1.00       892

    accuracy                           1.00      2113
   macro avg       1.00      1.00      1.00      2113
weighted avg       1.00      1.00      1.00      2113

